toolb = nuke.menu('Nodes')
toolb.addCommand('Add',"nuke.createNode('Add')")
toolb.addCommand('AddInputs',"nuke.createNode('AddInputs')")
toolb.addCommand('SimpleBlur',"nuke.createNode('SimpleBlur')")
toolb.addCommand('CatoGamma',"nuke.createNode('CatoGamma')")
toolb.addCommand("CatoContrast","nuke.createNode('CatoContrast')")
toolb.addCommand("CatoSharpen","nuke.createNode('CatoSharpen')")
toolb.addCommand("CatoEdge","nuke.createNode('CatoEdge')")
toolb.addCommand("CatoMedian", "nuke.createNode('CatoMedian')")